site_name: My Docs
theme:
    name: material

    # Color parameters
    palette:
        # Palette toggle pour le mode clair
        - scheme: default
          primary: light green
          accent: pink
          toggle:
              icon: material/brightness-4
              name: Passer en mode sombre

        # Palette toggle pour le mode sombre
        - scheme: slate
          primary: light green
          accent: pink
          toggle:
              icon: material/brightness-4
              name: Passer en mode clair

    features:
        - navigation.tabs
        - content.code.annotate
        - content.code.copy

nav:
    - Home: index.md
    - Architecture:
        - Présentation Générale: 
            - Schémas: architecture/schemas.md
            - Machines: architecture/machines.md
        - Arborescence fichiers: architecture/arborescence-fichiers.md    
    - Scripts:
        - Utilitaires Production: scripts/utilitaires-production.md
        - Utilitaires Installation: scripts/utilitaires-installation.md
        - Installation: 
            - Machine principale: 
                - Réseau: scripts/installation/vm-main/installation-reseau.md 
            - Serveur Web + SGBD: scripts/installation/installation-serveur-web.md


markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html

  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true

