#!/bin/bash


#
# --- install
#
# 1: nom
# 2: subnet
# 3: ip
# 4: {server|admin|user}
# 5: {2|66} 
check_and_install_connected_VM() {
    # la commande seed n'override pas le fichier qu'elle lit cela me permet 
    # d'utilise le meme modele pour chaque install

    # si la machine a besoin d'etre connecté a un serveur dhcp
    if [ -z $5 ]
    then
        # indiquer l'adresse du dhcp
            # première substitution de PATTERN-DHCP par le dernier octet de l'adresse ip du
            # dhcp {admin | user }
        # puis son nom
            # seconde substituion de PATTERN-NAME par le nom entré
        sed -e 's/PATTERN-DHCP/'$5'/g' modele-dhcp-preseed.cfg -e 's/PATTERN-NAME/'$1'/g'> preseed.cfg
    else # sinon c'est un serveur

        sed -e 's/PATTERN-SUB/'$2'/g' modele-preseed.cfg -e 's/PATTERN-ADDR/'$3'/g' -e 's/PATTERN-NAME/'$1'/g' > preseed.cfg
    fi
    if [[ -n $(virsh list --all | grep $1) ]]    
    then
    # desctruction de la machine si elle existe déjà
    virsh destroy  $1
    virsh undefine $1
    rm /var/lib/libvirt/images/$1.qcow2
    fi

    # installation de la via le script install
    ./install $1 $4
}

# verification des parrametres
# verification qu'un nom est present
if [ -z "$1" ]
then
    echo "le nom n'est pas valide"
    exit 1
fi

if ! [[ "$3" =~ ^[0-9]+$ ]]; then
  echo "Erreur: Le troisième argument doit être un entier."
  exit 1
fi


case "$2" in
        serveur)
                check_and_install_connected_VM $1 0 $3 $2
        ;;

        admin)
                check_and_install_connected_VM $1 1 $3 $2 2
        ;;

        user)
                check_and_install_connected_VM $1 1 $3 $2 66
        ;; 
        *)
        echo "Usage: $2 { serveur | admin | user }"
        ;;
esac






